version: '3'
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /web-project/student-frontend/logs:/fluentd/logs
    ports:
      - "24224:24224"
      - "24224:24224/udp"
