
- name: Check if docker-compose.yml exists
  stat:
    path: /logging/logging-data/docker-compose.yml
  register: compose_file

- name: Run Docker Compose Down
  shell: sudo docker compose down
  args:
    chdir: /logging/logging-data
  when: compose_file.stat.exists

- name: Remove logging directory
  file:
    path: /logging                
    state: absent

- name: Create directory logging  
  file:
    path: /logging       
    state: directory
    mode: '0755'

- name: Copy logging-data directory
  copy:
    src: logging-data
    dest: /logging

# - name: Create the file
#   file:
#     path: /logging/access.log.pos
#     state: touch
#     mode: "0664"

- name: Run Docker Compose Up
  shell: sudo docker compose up -d
  args:
    chdir: /logging/logging-data