---

# - hosts: all
#   become: true
#   tasks:
#   - name: update repository index (Ubuntu)
#     apt:
#       update_cache: true
#     when: ansible_distribution == "Ubuntu"

# - hosts: web_servers
#   become: true
#   roles:
#     - ../roles/web_servers

- hosts: web_clients
  become: true
  roles:
    - ../roles/logging_web

- hosts: web_servers
  become: true
  roles:
    - ../roles/logging_api

# - hosts: logging_server
#   become: true
#   roles:
#     - ../roles/logging_server