version: '3'

services:
  web_frontend:
    image: nginx
    ports:
      - 82:80
      - 8001:8001
    volumes:
      - ./src:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf